=== hxliujing/github-service-java/java-tcc-transaction/java-tcc-order/java-tcc-order-service/dalgen/config/table-config-1.0.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--
        -->
        <!ELEMENT table (column* | resultmap* | operation*)+>
        <!ATTLIST table
                sqlname CDATA #IMPLIED
                sequence CDATA #IMPLIED
                physicalName CDATA #IMPLIED
                remark CDATA #IMPLIED
                >
        <!--
        -->
        <!ELEMENT column EMPTY>
        <!ATTLIST column
                name CDATA #REQUIRED
                javatype CDATA #REQUIRED
                jdbctype CDATA #REQUIRED
                remark CDATA #REQUIRED
                relatedColumn CDATA #IMPLIED
                >

        <!--
         -->
        <!ELEMENT resultmap (column)*>
        <!ATTLIST resultmap
                name CDATA #REQUIRED
                type CDATA #REQUIRED
                remark CDATA #IMPLIED
                >
        <!--
        -->
        <!ELEMENT operation (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST operation
                name CDATA #REQUIRED
                paging CDATA #IMPLIED
                paramtype (object|primitive) #IMPLIED
                multiplicity (one|many|paging) #IMPLIED
                remark CDATA #IMPLIED
                resulttype CDATA #IMPLIED
                resultmap CDATA #IMPLIED
                timeout CDATA #IMPLIED
                >

        <!ELEMENT include EMPTY>
        <!ATTLIST include
                refid CDATA #REQUIRED
                >


        <!ELEMENT selectKey (#PCDATA | include)*>
        <!ATTLIST selectKey
                resultType CDATA #IMPLIED
                keyProperty CDATA #IMPLIED
                order (BEFORE|AFTER) #IMPLIED
                >

        <!-- - - - - - - - - - - - - - - - - - - - - - - - -
                         DYNAMIC ELEMENTS
          - - - - - - - - - - - - - - - - - - - - - - - - -->


        <!ELEMENT bind EMPTY>
        <!ATTLIST bind
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >

        <!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST trim
                prefix CDATA #IMPLIED
                prefixOverrides CDATA #IMPLIED
                suffix CDATA #IMPLIED
                suffixOverrides CDATA #IMPLIED
                >
        <!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST foreach
                collection CDATA #REQUIRED
                item CDATA #IMPLIED
                index CDATA #IMPLIED
                open CDATA #IMPLIED
                close CDATA #IMPLIED
                separator CDATA #IMPLIED
                >

        <!ELEMENT choose (when* , otherwise?)>
        <!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST when
                test CDATA #REQUIRED
                >
        <!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

        <!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
        <!ATTLIST if
                test CDATA #REQUIRED
                >

=== hxliujing/github-service-java/java-tcc-transaction/java-tcc-order/java-tcc-order-service/dalgen/tcc_java_orderTables/TCC_ORDER.xml
<!DOCTYPE table SYSTEM "../config/table-config-1.0.dtd">
    <table sqlname="TCC_ORDER" physicalName="TCC_ORDER"
    remark="TCC_ORDER">
<!--    &lt;&gt;   <> -->
<operation name="insert" paramtype="object" remark="insert:TCC_ORDER">
INSERT INTO TCC_ORDER
    <trim prefix="(" suffix=")" suffixOverrides=",">
        <if test="id != null">`ID`,</if>
        <if test="type != null">`TYPE`,</if>
        <if test="isDel != null">`IS_DEL`,</if>
        <if test="amount != null">`AMOUNT`,</if>
        <if test="orderSn != null">`ORDER_SN`,</if>
        <if test="accountId != null">`ACCOUNT_ID`,</if>
        <if test="createTime != null">`CREATE_TIME`,</if>
        <if test="updateTime != null">`UPDATE_TIME`,</if>
    </trim>
VALUES
    <trim prefix="(" suffix=")" suffixOverrides=",">
        <if test="id != null">#{id,jdbcType=INTEGER},</if>
        <if test="type != null">#{type,jdbcType=INTEGER},</if>
        <if test="isDel != null">#{isDel,jdbcType=TINYINT},</if>
        <if test="amount != null">#{amount,jdbcType=DECIMAL},</if>
        <if test="orderSn != null">#{orderSn,jdbcType=VARCHAR},</if>
        <if test="accountId != null">#{accountId,jdbcType=INTEGER},</if>
        <if test="createTime != null">#{createTime,jdbcType=TIMESTAMP},</if>
        <if test="updateTime != null">#{updateTime,jdbcType=TIMESTAMP},</if>
    </trim>
    </operation>


    <operation name="getById" multiplicity="one" remark="获取记录">
        SELECT * FROM TCC_ORDER WHERE id =#{id,jdbcType=INTEGER}  and IS_DEL = 0 LIMIT 1
    </operation>

    <operation name="getByIdForUpdate" multiplicity="one" remark="获取记录">
        SELECT * FROM TCC_ORDER WHERE id =#{id,jdbcType=INTEGER}  and IS_DEL = 0  FOR UPDATE
    </operation>

    <operation name="getByOrderSnForUpdate" multiplicity="one" remark="获取记录">
        SELECT * FROM TCC_ORDER WHERE ORDER_SN =#{orderSn,jdbcType=VARCHAR}  and IS_DEL = 0  FOR UPDATE
    </operation>

    </table>

=== hxliujing/github-service-java/java-tcc-transaction/java-tcc-account/java-tcc-account-service/dalgen/tcc_java_accountTables/TCC_ACCOUNT.xml
<!DOCTYPE table SYSTEM "../config/table-config-1.0.dtd">
    <table sqlname="TCC_ACCOUNT" physicalName="TCC_ACCOUNT"
    remark="TCC_ACCOUNT">
<!--    &lt;&gt;   <> -->
<operation name="insert" paramtype="object" remark="insert:TCC_ACCOUNT">
INSERT INTO TCC_ACCOUNT
    <trim prefix="(" suffix=")" suffixOverrides=",">
        <if test="id != null">`ID`,</if>
        <if test="type != null">`TYPE`,</if>
        <if test="isDel != null">`IS_DEL`,</if>
        <if test="amount != null">`AMOUNT`,</if>
        <if test="createTime != null">`CREATE_TIME`,</if>
        <if test="updateTime != null">`UPDATE_TIME`,</if>
    </trim>
VALUES
    <trim prefix="(" suffix=")" suffixOverrides=",">
        <if test="id != null">#{id,jdbcType=INTEGER},</if>
        <if test="type != null">#{type,jdbcType=INTEGER},</if>
        <if test="isDel != null">#{isDel,jdbcType=TINYINT},</if>
        <if test="amount != null">#{amount,jdbcType=DECIMAL},</if>
        <if test="createTime != null">#{createTime,jdbcType=TIMESTAMP},</if>
        <if test="updateTime != null">#{updateTime,jdbcType=TIMESTAMP},</if>
    </trim>
    </operation>



    <operation name="getById" multiplicity="one" remark="获取记录">
        SELECT * FROM TCC_ACCOUNT WHERE id =#{id,jdbcType=INTEGER}  and IS_DEL = 0 LIMIT 1
    </operation>

    <operation name="getByIdForUpdate" multiplicity="one" remark="获取记录">
        SELECT * FROM TCC_ACCOUNT WHERE id =#{id,jdbcType=INTEGER}  and IS_DEL = 0  FOR UPDATE
    </operation>


    <operation name="updateAccountBalance"  paramtype="object"  remark="修改账户金额">
        UPDATE TCC_ACCOUNT SET  amount = amount + #{amount,jdbcType=DECIMAL}
        where
        id = #{id,jdbcType=INTEGER} and IS_DEL = 0
    </operation>
    </table>
